"""baseline schema

Revision ID: b8bec1855043
Revises: 
Create Date: 2025-11-03 11:20:29.260817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bec1855043'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_label', sa.String(), nullable=False),
    sa.Column('image_base64', sa.Text(), nullable=False),
    sa.Column('image_mime_type', sa.String(), nullable=True),
    sa.Column('image_color', sa.String(), nullable=False),
    sa.Column('image_font', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_label')
    )
    op.create_table('badges',
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('unique_id')
    )
    op.create_table('work_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('image_label', sa.String(), nullable=False),
    sa.Column('image_base64', sa.Text(), nullable=False),
    sa.Column('image_mime_type', sa.String(), nullable=True),
    sa.Column('image_color', sa.String(), nullable=False),
    sa.Column('image_font', sa.String(), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=True),
    sa.Column('text_x', sa.Integer(), nullable=True),
    sa.Column('text_y', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('badge_images',
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('image_label', sa.String(), nullable=False),
    sa.Column('image_base64', sa.Text(), nullable=False),
    sa.Column('image_mime_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['unique_id'], ['badges.unique_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unique_id', 'image_label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badge_images')
    op.drop_table('work_queue')
    op.drop_table('badges')
    op.drop_table('available_images')
    # ### end Alembic commands ###
