"""initial schema

Revision ID: e608625baeeb
Revises: 
Create Date: 2025-11-11 12:53:55.859897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e608625baeeb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_label', sa.String(), nullable=False),
    sa.Column('requires_secret_code', sa.Boolean(), nullable=False),
    sa.Column('secret_code', sa.String(), nullable=True),
    sa.Column('image_base64', sa.Text(), nullable=False),
    sa.Column('image_mime_type', sa.String(), nullable=True),
    sa.Column('image_color', sa.String(), nullable=False),
    sa.Column('image_font', sa.String(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_label')
    )
    op.create_table('badges',
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mac_address', sa.String(length=23), nullable=True),
    sa.Column('firmware_base64', sa.Text(), nullable=True),
    sa.Column('firmware_hash', sa.String(length=16), nullable=True),
    sa.Column('selected_image_label', sa.String(), nullable=True),
    sa.Column('selected_image_base64', sa.Text(), nullable=True),
    sa.Column('selected_image_mime_type', sa.String(), nullable=True),
    sa.Column('selected_image_color', sa.String(), nullable=True),
    sa.Column('selected_image_font', sa.String(), nullable=True),
    sa.Column('selected_font_size', sa.Integer(), nullable=True),
    sa.Column('selected_text_x', sa.Integer(), nullable=True),
    sa.Column('selected_text_y', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('unique_id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_table('badge_images',
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('image_label', sa.String(), nullable=False),
    sa.Column('image_base64', sa.Text(), nullable=False),
    sa.Column('image_mime_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['unique_id'], ['badges.unique_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unique_id', 'image_label')
    )
    op.create_table('badge_unlocked_images',
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.Column('image_label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['unique_id'], ['badges.unique_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unique_id', 'image_label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badge_unlocked_images')
    op.drop_table('badge_images')
    op.drop_table('badges')
    op.drop_table('available_images')
    # ### end Alembic commands ###
